env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {
    'arrow-body-style': ['error', 'always'],
    'import/no-extraneous-dependencies':
      [
        'error',
        {
          'devDependencies': true,
          'optionalDependencies': true,
          'peerDependencies': true,
        },
      ],
     
"react/function-component-definition": [<enabled>, {
  "namedComponents": "function-declaration" | "function-expression" | "arrow-function" | Array<"function-declaration" | "function-expression" | "arrow-function">,
  "unnamedComponents": "function-expression" | "arrow-function" | Array<"function-expression" | "arrow-function">
}]

  }
