import React,{useState} from 'react'
import Head from 'next/head';
import Router, { useRouter } from 'next/router'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import{validateEmail} from "../components/utils/utils"
import { InputEmail,Button,FormControl,H2,Hyperlink } from '../components'


export default function Forget() {
  const router=useRouter()
  const[formValue,setFormValue]=useState({email:''})
 
  const handleOnChange=(name,value)=>{
   setFormValue({...formValue,[name]:value})
  }

 const handleSubmit=(e)=>{
  if(e){ e.preventDefault()}
  
if(validateEmail(formValue.email)){
  
    console.log('sucess',formValue);
      router.push('/')
 
}

 
 }
  return (
    <div >
      <Head>
        <title>بازیابی کلمه عبور</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
      <H2 align='center'>لطفا ایمیل خود را وارد کنید</H2>
        <form onSubmit={handleSubmit}>
          <FormControl>
            <InputEmail onChange={(value)=>handleOnChange('email',value)} placeholder="ایمیل"/>
          </FormControl>
          
        <FormControl>
        <Button type="submit">بازیابی کلمه عبور</Button>
        </FormControl>

        
        <Hyperlink href='/'>
        برو به صفحه ی اصلی
        </Hyperlink>

      

        </form>
       
        
      </LayoutAuth>
    </div>
  )
}
