import React,{useState} from 'react'
import Head from 'next/head';
import  { useRouter } from 'next/router'
import { useDispatch,useSelector } from 'react-redux';

import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import{validateEmail,validateSubject} from "../components/utils/utils"
import { Hyperlink,InputEmail, InputPassword,Button,FormControl,H2, InputText } from '../components'
import { REGISTER_ACTION } from '../actions';

export default function register() {
  const dispatch=useDispatch()
  const {loading}=useSelector(state=>state.auth)
  const router=useRouter()
  const[formValue,setFormValue]=useState({email:'',password:'',username:''})
 
  const handleOnChange=(name,value)=>{
   setFormValue({...formValue,[name]:value})
  }

 const handleSubmit=(e)=>{
  if(e){ e.preventDefault()}
  console.log('sucess',formValue);
  dispatch(REGISTER_ACTION())

    router.push('/')


  // if(!validateEmail(formValue.email)){
  //   console.log('your email is wrong!')
  // }
  
  // if(!validateSubject(formValue.password)){
  //   console.log('your pass is wrong!')
  // }
  // if(validateEmail(formValue.email) && validateSubject(formValue.password)){
  //   console.log('sucess',formValue);
  //   router.push('/')
  // }
 
 }
  return (
    <div >
      <Head>
        <title>ثبت نام </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
      <H2 align='center'>لطفا اطلاعات خود را وارد کنید</H2>
        <form onSubmit={handleSubmit}>
        <FormControl>
            <InputText onChange={(value)=>handleOnChange('username',value)} placeholder="نام کاربری" autoComplete='true' required={true}/>
          </FormControl>
          <FormControl>
            <InputEmail onChange={(value)=>handleOnChange('email',value)} placeholder="ایمیل"/>
          </FormControl>
          <FormControl>
            <InputPassword onChange={(value)=>handleOnChange('password',value)} placeholder="کلمه عبور"/>
          </FormControl>
        <FormControl>
        <Button type="submit" loading={loading}>ثبت نام</Button>
        </FormControl>
        </form>
        <Hyperlink href='/login'>
          صفحه ی ورود
        </Hyperlink><br/>
        
      </LayoutAuth>
    </div>
  )
}
