import React,{useState} from 'react'
import Head from 'next/head';
import  { useRouter } from 'next/router'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import {  InputPassword,Button,FormControl,H2, InputText, Hyperlink } from '../components'


export default function Reset() {
  const router=useRouter()
  const[formValue,setFormValue]=useState({password:'',repassword:''})
 
  const handleOnChange=(name,value)=>{
   setFormValue({...formValue,[name]:value})
  }

 const handleSubmit=(e)=>{
  if(e){ e.preventDefault()}
  
if(formValue.password && formValue.repassword && formValue.password===formValue.repassword){
  
    console.log('sucess',formValue);
      router.push('/')
 
}
else{
  console.log('password is wrong')
}
 
 }
  return (
    <div >
      <Head>
        <title>تغییر کلمه عبور</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
      <H2 align='center'>لطفا رمز عبور جدید خود را وارد کنید</H2>
        <form onSubmit={handleSubmit}>
          <FormControl>
            <InputPassword onChange={(value)=>handleOnChange('password',value)} placeholder="کلمه عبور"/>
          </FormControl>
          <FormControl>
            <InputPassword onChange={(value)=>handleOnChange('passwordNew',value)} placeholder="تکرار کلمه عبور"/>
          </FormControl>
        <FormControl>
        <Button type="submit">تغییر رمز</Button>
        </FormControl>

        <Hyperlink href='/login'>
              صفحه ی ورود
        </Hyperlink>

        <Hyperlink href='/'>
          صفحه ی اصلی  
         </Hyperlink>
        <Hyperlink href='/register'>
          صفحه ی ثبت نام
        </Hyperlink>
        </form>
      
        
      </LayoutAuth>
    </div>
  )
}
